services:
  bench-node:
    build: ./bench-node
    container_name: bench-node
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    cpus: 1.0
    mem_limit: 512mb
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  bench-ovencord:
    build: ./bench-ovencord
    container_name: bench-ovencord
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    cpus: 1.0
    mem_limit: 512mb
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
